# Generated by Django 4.2.4 on 2023-08-22 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("loco_transact_sync", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("depth", models.PositiveIntegerField()),
                (
                    "ancestor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="descendant_links",
                        to="loco_transact_sync.transaction",
                    ),
                ),
                (
                    "descendant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ancestor_links",
                        to="loco_transact_sync.transaction",
                    ),
                ),
            ],
        ),
    ]
